// ══════════════════════════════════════════════
// nexus/lib/integrations/brevo.js
// Create Brevo contact list + email campaigns
// from the businessAgent's email sequence output.
//
// Flow:
//  1. Parse the 5-email markdown block into structured objects
//  2. Create a new Contact List for this business
//  3. Create each email as a Brevo draft EmailCampaign
//  4. Return { listId, campaignIds, campaignCount }
//
// Env var required: BREVO_API_KEY
// Fallback: returns null gracefully if key missing
// ══════════════════════════════════════════════

import fetch from 'node-fetch';

const BASE_URL    = 'https://api.brevo.com/v3';
const DELAYS_DAYS = [0, 2, 4, 7, 14]; // J+0, J+2, J+4, J+7, J+14

function brevoHeaders() {
  const key = process.env.BREVO_API_KEY;
  if (!key) throw new Error('BREVO_API_KEY non configurée');
  return {
    'api-key':      key,
    'Content-Type': 'application/json',
    Accept:         'application/json',
  };
}

/**
 * Parse the markdown email sequence generated by writeAgent into
 * an array of { subject, body, delayDays } objects.
 * Expects format: "## Email N — Sujet: ...\n**Délai**: J+X\n**Corps**: ..."
 *
 * @param {string} emailsMarkdown
 * @param {string} businessName
 * @returns {Array<{subject: string, body: string, delayDays: number}>}
 */
export function parseEmailSequence(emailsMarkdown, businessName) {
  const emails = [];
  // Split on "## Email" headers
  const blocks = emailsMarkdown.split(/##\s*Email\s*\d+/i).filter(b => b.trim());

  blocks.forEach((block, i) => {
    // Extract subject
    const subjectMatch = block.match(/Sujet\s*[:\-]\s*(.+)/i)
                      || block.match(/\*\*Sujet\*\*\s*[:\-]\s*(.+)/i);
    const subject = subjectMatch
      ? subjectMatch[1].trim().replace(/\*\*/g, '')
      : `${businessName} — Email ${i + 1}`;

    // Extract body (everything after subject/délai headers)
    const bodyMatch = block.match(/(?:\*\*Corps\*\*|Corps)\s*[:\-]\s*([\s\S]+)/i)
                   || block.match(/(?:Délai[^]*?\n)([\s\S]+)/i);
    const body = bodyMatch
      ? bodyMatch[1].trim()
      : block.replace(/Sujet[^\n]+\n/i, '').replace(/Délai[^\n]+\n/i, '').trim();

    emails.push({
      subject,
      body:      body.slice(0, 20000), // Brevo HTML content limit
      delayDays: DELAYS_DAYS[i] ?? i * 3,
    });
  });

  // If parsing failed entirely, create fallback entries
  if (emails.length === 0) {
    return DELAYS_DAYS.map((delay, i) => ({
      subject:   `${businessName} — ${['Bienvenue', 'Fonctionnalité clé', 'Cas d\'usage', 'Upgrade Pro', 'On vous manque ?'][i]}`,
      body:      emailsMarkdown.slice(i * 300, (i + 1) * 300) || `Email ${i + 1} pour ${businessName}`,
      delayDays: delay,
    }));
  }

  return emails.slice(0, 5); // max 5 emails
}

/**
 * Create a Brevo Contact List for this business.
 * @param {string} businessName
 * @returns {Promise<number>}  listId
 */
async function createContactList(businessName) {
  const listName = `${businessName}_leads_${Date.now().toString(36)}`;
  const resp = await fetch(`${BASE_URL}/contacts/lists`, {
    method:  'POST',
    headers: brevoHeaders(),
    body:    JSON.stringify({ name: listName }),
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({}));
    throw new Error(`Brevo createList failed (${resp.status}): ${err.message || resp.statusText}`);
  }
  const data = await resp.json();
  return data.id;
}

/**
 * Create a single Brevo email campaign (draft).
 * @param {Object} opts
 * @param {string} opts.subject
 * @param {string} opts.htmlContent
 * @param {string} opts.businessName
 * @param {number} opts.listId
 * @param {number} opts.emailIndex   1-based index for campaign name
 * @returns {Promise<number>}  campaignId
 */
async function createCampaign({ subject, htmlContent, businessName, listId, emailIndex }) {
  const senderEmail = process.env.BREVO_SENDER_EMAIL || 'nexus@nexus-ai.app';
  const senderName  = process.env.BREVO_SENDER_NAME  || businessName;

  // Wrap plain text body in minimal HTML if needed
  const html = htmlContent.trimStart().startsWith('<')
    ? htmlContent
    : `<html><body style="font-family:sans-serif;max-width:600px;margin:auto;padding:24px">
        ${htmlContent.replace(/\n\n/g, '</p><p>').replace(/\n/g, '<br>')}
      </body></html>`;

  const resp = await fetch(`${BASE_URL}/emailCampaigns`, {
    method:  'POST',
    headers: brevoHeaders(),
    body:    JSON.stringify({
      name:     `[${businessName}] Email ${emailIndex} — ${subject.slice(0, 50)}`,
      subject,
      sender:   { name: senderName, email: senderEmail },
      type:     'classic',
      htmlContent: html,
      recipients: { listIds: [listId] },
      // status 'draft' is the default — no scheduledAt = stays as draft
    }),
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({}));
    throw new Error(`Brevo createCampaign #${emailIndex} failed (${resp.status}): ${err.message || resp.statusText}`);
  }
  const data = await resp.json();
  return data.id;
}

/**
 * Create a full Brevo email sequence for a business.
 * Creates: 1 contact list + up to 5 email campaign drafts.
 * Falls back gracefully if BREVO_API_KEY is missing.
 *
 * @param {string} emailsMarkdown   Output from writeAgent
 * @param {string} businessName     e.g. "newsletter_ia"
 * @returns {Promise<{listId: number|null, campaignIds: number[], campaignCount: number, error?: string}|null>}
 */
export async function createBrevoSequence(emailsMarkdown, businessName) {
  if (!process.env.BREVO_API_KEY) {
    console.warn('[Brevo] BREVO_API_KEY absente — séquence email ignorée');
    return { listId: null, campaignIds: [], campaignCount: 0, error: 'BREVO_API_KEY manquante' };
  }

  try {
    const emails = parseEmailSequence(emailsMarkdown, businessName);
    console.log(`[Brevo] Création liste contacts + ${emails.length} campagnes pour: ${businessName}`);

    const listId = await createContactList(businessName);
    console.log(`[Brevo] Liste créée: id=${listId}`);

    const campaignIds = [];
    for (let i = 0; i < emails.length; i++) {
      const { subject, body, delayDays } = emails[i];
      try {
        const id = await createCampaign({
          subject,
          htmlContent: body,
          businessName,
          listId,
          emailIndex: i + 1,
        });
        campaignIds.push(id);
        console.log(`[Brevo] ✅ Campagne #${i + 1} créée (id=${id}, J+${delayDays}): ${subject.slice(0, 50)}`);
      } catch (err) {
        // Don't abort whole sequence on one failed campaign
        console.warn(`[Brevo] ⚠️ Campagne #${i + 1} ignorée: ${err.message}`);
      }
    }

    return { listId, campaignIds, campaignCount: campaignIds.length };
  } catch (err) {
    console.error('[Brevo] Erreur séquence:', err.message);
    return { listId: null, campaignIds: [], campaignCount: 0, error: err.message };
  }
}
